# Generated by Django 3.2.12 on 2022-02-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_division_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
