# Generated by Django 3.2.12 on 2022-03-01 09:22

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_app', '0003_staff_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question1', models.CharField(max_length=400, null=True)),
                ('answer1', models.CharField(max_length=400, null=True)),
                ('options1', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), default=list, null=True, size=10)),
                ('Question2', models.CharField(max_length=400, null=True)),
                ('answer2', models.CharField(max_length=400, null=True)),
                ('options2', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), default=list, null=True, size=10)),
                ('Question3', models.CharField(max_length=400, null=True)),
                ('answer3', models.CharField(max_length=400, null=True)),
                ('options3', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), default=list, null=True, size=10)),
                ('Question4', models.CharField(max_length=400, null=True)),
                ('answer4', models.CharField(max_length=400, null=True)),
                ('options4', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), default=list, null=True, size=10)),
                ('Question5', models.CharField(max_length=400, null=True)),
                ('answer5', models.CharField(max_length=400, null=True)),
                ('options5', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), default=list, null=True, size=10)),
                ('status', models.CharField(max_length=30, null=True)),
                ('expire', models.CharField(max_length=30, null=True)),
                ('Division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.division')),
                ('Staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.staff')),
                ('Users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
