# Generated by Django 3.2.12 on 2022-03-01 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_app', '0004_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question1', models.CharField(max_length=400, null=True)),
                ('answer1', models.CharField(max_length=400, null=True)),
                ('Question2', models.CharField(max_length=400, null=True)),
                ('answer2', models.CharField(max_length=400, null=True)),
                ('Question3', models.CharField(max_length=400, null=True)),
                ('answer3', models.CharField(max_length=400, null=True)),
                ('Question4', models.CharField(max_length=400, null=True)),
                ('answer4', models.CharField(max_length=400, null=True)),
                ('Question5', models.CharField(max_length=400, null=True)),
                ('answer5', models.CharField(max_length=400, null=True)),
                ('status', models.CharField(max_length=30, null=True)),
                ('expire', models.CharField(max_length=30, null=True)),
                ('Staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.staff')),
                ('Student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.users')),
                ('Users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
