# Generated by Django 3.2.12 on 2022-03-02 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='Division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.division'),
        ),
    ]
