# Generated by Django 3.2.12 on 2022-03-19 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_answers_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=400, null=True)),
                ('card_number', models.CharField(max_length=400, null=True)),
                ('expire', models.CharField(max_length=400, null=True)),
                ('csv', models.CharField(max_length=400, null=True)),
                ('amount', models.CharField(max_length=400, null=True)),
                ('Users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.users')),
            ],
        ),
    ]
